### ISSUE TITLE
Composer installation

### ISSUE THREAD

**Issue by teppokoivula** [Toutouwai/UniqueImageVariations#2]
Hey Robin,

As the title states, I'd appreciate if you could add support for composer installation (i.e. add composer.json and submit the module to Packagist).

This is related to an issue I opened for MinimalFieldset: https://github.com/Toutouwai/MinimalFieldset/issues/3. Basically the same config would work too, except that the package name would (of course) be toutouwai/unique-image-variations.

Thanks again for considering :)

**Comment by Toutouwai** [comment]
Hi Teppo, I've added this module to Packagist too.
